### ISSUE TITLE
save figures instead of showing them in browser.

### ISSUE THREAD

**Issue by alexpvpmindustry** [gran4/AI-InvestiBot#99]
**Is your feature request related to a problem? Please describe.**
most times, I don't want to just view the figures.
i like to save them instead, or at least the code have to have an option to do so.

**Describe the solution you'd like**
maybe add a `save_graph` attribute? to the basic model class?

**Describe alternatives you've considered**
IMO, models class should be purely models, and plotting should have been another completely separate module.

**Additional context**
maybe we can use mplfinance to do part of the plottings.

**Comment by gran4** [comment]
Do model.save().

P.S: ALSO, there is an option to test the model but not graph. Just do model.test(show_graph=False)

P.P.S: I had the same idea about splitting the plotting into a function, but I have not gotten around to that
